name: Validate activation
on:
  workflow_dispatch: {}
jobs:
  activation:
    name: Validate activation 🔑
    runs-on: ubuntu-latest
    steps:
      - name: Unity - Activate
        uses: game-ci/unity-activate@v2.0.0
        with:
          unityVersion: 2022.2.1f1